name: CI

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]
        gemfile:
          - jwt_2
          - jwt_3

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v6

    - run: rm Gemfile.lock

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}

    - name: Run tests
      run: bundle exec rspec
